CREATE TABLE [dbo].[Customer]
(	
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(50) NOT NULL,
	[PhoneNumber] NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
)
